version: "3"
services:
  locust-worker:
    container_name: locust-worker
    image: locustio/locust
    volumes:
      - ./locust/:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host 192.168.88.102
    networks:
      management_network:
       
networks:
  management_network:
    driver: bridge
