# Use with: kind create cluster --config kind-config.yaml

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
# Control plane nodes
  - role: control-plane 
    extraPortMappings:
    - containerPort: 32080
      hostPort: 8080
    - containerPort: 32443
      hostPort: 8443

  # Worker nodes
  - role: worker
