# Use with: kind create cluster --config kind-config.yaml

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
  # the control plane node config
  - role: control-plane
    kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "ingress-ready=true"
      extraPortMappings:
      - containerPort: 32080
        hostPort: 80
      - containerPort: 32443
        hostPort: 443

  # the three workers
  - role: worker
