kind: Deployment
apiVersion: apps/v1
metadata:
  name: crab
  labels:
    app: crab

spec:
  replicas: 1
  selector:
    matchLabels:
      app: crab
  template:
    metadata:
      labels:
        app: crab
    spec:
      containers:
        - name: crab
          image: movie/crab
          imagePullPolicy: Never
          ports:
            - name: web
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: crab

spec:
  ports:
    - name: web
      port: 80
      targetPort: web

  selector:
    app: crab
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix
spec:
  stripPrefix:
    prefixes:
      - /movie
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crab-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: default-strip-prefix@kubernetescrd
spec:
  rules:
  - http:
      paths:
      - path: /movie
        pathType: Prefix
        backend:
          service:
            name: crab
            port:
              name: web
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: crab-scaledobject
spec:
  scaleTargetRef:
    name: crab
  pollingInterval: 5
  cooldownPeriod:  30
  minReplicaCount: 1
  maxReplicaCount: 10
  advanced:
    restoreToOriginalReplicaCount: true       
    horizontalPodAutoscalerConfig:
      name: crab-scaledobject                 
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 10
          policies:
          - type: Pods
            value: 1
            periodSeconds: 5
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-server:80
        threshold: '100'
        query: sum(rate(traefik_service_requests_total{service="default-crab-web@kubernetes"}[2m])) # / sum(kube_deployment_status_replicas_available{deployment="crab"})
