kind: Deployment
apiVersion: apps/v1
metadata:
  name: snake
  labels:
    app: snake

spec:
  replicas: 1
  selector:
    matchLabels:
      app: snake
  template:
    metadata:
      labels:
        app: snake
    spec:
      containers:
        - name: snake
          image: aschil/snake
          ports:
            - name: web
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: snake

spec:
  ports:
    - name: web
      port: 80
      targetPort: web

  selector:
    app: snake
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: snake-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: snake
            port:
              name: web
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: snake-scaledobject
spec:
  scaleTargetRef:
    name: snake
  pollingInterval: 5
  cooldownPeriod:  30
  minReplicaCount: 1
  maxReplicaCount: 10
  advanced:
    restoreToOriginalReplicaCount: true       
    horizontalPodAutoscalerConfig:
      name: snake-scaledobject                 
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 10
          policies:
          - type: Pods
            value: 1
            periodSeconds: 5
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-server:80
        threshold: '100'
        query: sum(rate(traefik_service_requests_total{service="default-snake-web@kubernetes"}[2m])) / sum(kube_deployment_status_replicas_available{deployment="snake"})