kind: Deployment
apiVersion: apps/v1
metadata:
  name: whoami
  labels:
    app: whoami

spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami
          image: traefik/whoami
          ports:
            - name: web
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: whoami

spec:
  ports:
    - name: web
      port: 80
      targetPort: web

  selector:
    app: whoami
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami-ingress
spec:
  rules:
  - http:
      paths:
      - path: /whoami
        pathType: Prefix
        backend:
          service:
            name: whoami
            port:
              name: web
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: whoami-scaledobject
spec:
  scaleTargetRef:
    name: whoami
  pollingInterval: 5
  cooldownPeriod:  30
  minReplicaCount: 1
  maxReplicaCount: 10
  advanced:
    restoreToOriginalReplicaCount: true       
    horizontalPodAutoscalerConfig:
      name: whoami-scaledobject                 
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 10
          policies:
          - type: Pods
            value: 1
            periodSeconds: 5
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-server:80
        threshold: '100'
        query: sum(rate(traefik_service_requests_total{service="default-whoami-web@kubernetes"}[2m])) # / sum(kube_deployment_status_replicas_available{deployment="whoami"})
